version: "3.7"

services:
  database: 
    image: mysql:5.7
    container_name: store-mysql
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_USER=sealteam
    - MYSQL_PASSWORD=sckshuhari
    - MYSQL_DATABASE=store
    volumes:
    - ./tearup/:/docker-entrypoint-initdb.d/
    ports:
    - "3301:3302"
  
  xmysql:
    image: markuman/xmysql:0.4.2
    container_name: xmysql
    environment:
      - DATABASE_HOST=database
      - DATABASE_USER=sealteam
      - DATABASE_PASSWORD=sckshuhari
      - DATABASE_NAME=store
    depends_on:
      - database
    ports:
      - "3302:80"



        